In [ ]:
import numpy as np
import pandas as pd

df2 = pd.DataFrame(columns=['Name', 'Age', 'Gender', 'Email'])

def edit_row(df2, row_index, name, age, gender, email):
    if row_index < len(df2):
        df2.loc[row_index, 'Name'] = name
        df2.loc[row_index, 'Age'] = age
        df2.loc[row_index, 'Gender'] = gender
        df2.loc[row_index, 'Email'] = email
        return df2

def delete_row(df2, row_index):
    if row_index < len(df2):
        df2.drop(df2.index[row_index], inplace=True)
        return df2

def add_row(df2, name, age, gender, email):
    new_row = {'Name': name, 'Age': age, 'Gender': gender, 'Email': email}
    df2.loc[len(df2)] = new_row

    
    return df2

# Function to display the DataFrame
def display_df(df2):
    print(df2)
    print()

    print(f"Total rows: {len(df2)}")
    print()

    print(f"Average age: {df2['Age'].mean()}")
    print()


    print(f"Males: {len(df2[df2['Gender'] == 'Male'])}")
    print(f"Females: {len(df2[df2['Gender'] == 'Female'])}")


def filter_df(df2, column, value):
    filtered_df = df2[df2[column] == value]
    return filtered_df

#â—‹ Sort the data by a column (e.g., age).
def sort_df(df2, column):
    sorted_df = df2.sort_values(by=column)
    return sorted_df


df2 = pd.DataFrame(columns=['Name', 'Age', 'Gender', 'Email'])
df2 = add_row(df2, 'John', 25, 'Male', 'john@yahoo.com')
df2 = add_row(df2, 'Jane', 30, 'Female', 'jane@gmail.com')
df2 = add_row(df2, 'Mike', 20, 'Male', 'mike@gmail.com')
df2 = add_row(df2, 'Emma', 35, 'Female', 'emma@yahoo.com')
df2 = add_row(df2, 'Tom', 40, 'Male', 'tom@gmail.com')
df2 = add_row(df2, 'Lily', 45, 'Female','Lily@yahoo.com')
display_df(df2)


df2 = edit_row(df2, 1, 'Jane Smith', 27, 'Female', 'janesmith@gmail.com')
display_df(df2)


df2 = delete_row(df2, 1)
display_df(df2)

df3 = filter_df(df2, 'Age', 25)
display_df(df3)

df2 = sort_df(df2, 'Age')
display_df(df2)

df2.to_csv('project_panda.csv', index=False)

   Name  Age  Gender           Email
0  John   25    Male  john@yahoo.com
1  Jane   30  Female  jane@gmail.com
2  Mike   20    Male  mike@gmail.com
3  Emma   35  Female  emma@yahoo.com
4   Tom   40    Male   tom@gmail.com
5  Lily   45  Female  Lily@yahoo.com

Total rows: 6

Average age: 32.5

Males: 3
Females: 3
         Name  Age  Gender                Email
0        John   25    Male       john@yahoo.com
1  Jane Smith   27  Female  janesmith@gmail.com
2        Mike   20    Male       mike@gmail.com
3        Emma   35  Female       emma@yahoo.com
4         Tom   40    Male        tom@gmail.com
5        Lily   45  Female       Lily@yahoo.com

Total rows: 6

Average age: 32.0

Males: 3
Females: 3
   Name  Age  Gender           Email
0  John   25    Male  john@yahoo.com
2  Mike   20    Male  mike@gmail.com
3  Emma   35  Female  emma@yahoo.com
4   Tom   40    Male   tom@gmail.com
5  Lily   45  Female  Lily@yahoo.com

Total rows: 5

Average age: 33.0

Males: 3
Females: 2
   Name  Age Gender           Email
0  John   25   Male  john@yahoo.com

Total rows: 1

Average age: 25.0

Males: 1
Females: 0
   Name  Age  Gender           Email
2  Mike   20    Male  mike@gmail.com
0  John   25    Male  john@yahoo.com
3  Emma   35  Female  emma@yahoo.com
4   Tom   40    Male   tom@gmail.com
5  Lily   45  Female  Lily@yahoo.com

Total rows: 5

Average age: 33.0

Males: 3
Females: 2